### ISSUE TITLE
ODSay API 반환값

### ISSUE THREAD

**Issue by Leesungsup** [OpenSW-TeamLC/Angel-Kitchen#2]
"result": {
		"searchType": 0,
		"outTrafficCheck": 0,
		"busCount": 5,
		"subwayCount": 2,
		"subwayBusCount": 5,
		"pointDistance": 21703,
		"startRadius": 700,
		"endRadius": 700,
		"path": [
			{
				"pathType": 1,
				"info": {
					"trafficDistance": 33500,
					"totalWalk": 800,
					"totalTime": 77,
					"payment": 1650,
					"busTransitCount": 0,
					"subwayTransitCount": 1,
					"mapObj": "3:2:322:352",
					"firstStartStation": "불광",
					"lastEndStation": "오금",
					"totalStationCount": 30,
					"busStationCount": 0,
					"subwayStationCount": 30,
					"totalDistance": 34300,
					"totalWalkTime": -1
				},
				"subPath": [
					{
						"trafficType": 3,
						"distance": 498,
						"sectionTime": 7
					},
					{
						"trafficType": 1,
						"distance": 33500,
						"sectionTime": 65,
						"stationCount": 30,
						"lane": [
							{
								"name": "수도권 3호선",
								"subwayCode": 3,
								"subwayCityCode": 1000
							}
						],
						"startName": "불광",
						"startX": 126.93023,
						"startY": 37.610072,
						"endName": "오금",
						"endX": 127.128827,
						"endY": 37.502685,
						"way": "오금",
						"wayCode": 2,
						"door": "null",
						"startID": 322,
						"endID": 352,
						"startExitNo": "8",
						"startExitX": 126.92942479858755,
						"startExitY": 37.6113036211095,
						"endExitNo": "4",
						"endExitX": 127.12795185125601,
						"endExitY": 37.50154899799292,
						"passStopList": {
							"stations": [
								{
									"index": 0,
									"stationID": 322,
									"stationName": "불광",
									"x": "126.930237",
									"y": "37.610076"
								},
								{
									"index": 1,
									"stationID": 323,
									"stationName": "녹번",
									"x": "126.93578",
									"y": "37.600879"
								},
								{
									"index": 2,
									"stationID": 324,
									"stationName": "홍제",
									"x": "126.944113",
									"y": "37.588803"
								},
								{
									"index": 3,
									"stationID": 325,
									"stationName": "무악재",
									"x": "126.950266",
									"y": "37.582506"
								},
								{
									"index": 4,
									"stationID": 326,
									"stationName": "독립문",
									"x": "126.957915",
									"y": "37.574457"
								},
								{
									"index": 5,
									"stationID": 327,
									"stationName": "경복궁",
									"x": "126.973567",
									"y": "37.575879"
								},
								{
									"index": 6,
									"stationID": 328,
									"stationName": "안국",
									"x": "126.98549",
									"y": "37.576565"
								},
								{
									"index": 7,
									"stationID": 329,
									"stationName": "종로3가",
									"x": "126.991842",
									"y": "37.571657"
								},
								{
									"index": 8,
									"stationID": 330,
									"stationName": "을지로3가",
									"x": "126.992629",
									"y": "37.566388"
								},
								{
									"index": 9,
									"stationID": 331,
									"stationName": "충무로",
									"x": "126.994728",
									"y": "37.560997"
								},
								{
									"index": 10,
									"stationID": 332,
									"stationName": "동대입구",
									"x": "127.005635",
									"y": "37.559078"
								},
								{
									"index": 11,
									"stationID": 333,
									"stationName": "약수",
									"x": "127.011001",
									"y": "37.554347"
								},
								{
									"index": 12,
									"stationID": 334,
									"stationName": "금호",
									"x": "127.015801",
									"y": "37.548279"
								},
								{
									"index": 13,
									"stationID": 335,
									"stationName": "옥수",
									"x": "127.017374",
									"y": "37.541609"
								},
								{
									"index": 14,
									"stationID": 336,
									"stationName": "압구정",
									"x": "127.028513",
									"y": "37.52633"
								},
								{
									"index": 15,
									"stationID": 337,
									"stationName": "신사",
									"x": "127.020402",
									"y": "37.516484"
								},
								{
									"index": 16,
									"stationID": 338,
									"stationName": "잠원",
									"x": "127.011629",
									"y": "37.512967"
								},
								{
									"index": 17,
									"stationID": 339,
									"stationName": "고속터미널",
									"x": "127.004975",
									"y": "37.504906"
								},
								{
									"index": 18,
									"stationID": 340,
									"stationName": "교대",
									"x": "127.01382",
									"y": "37.493031"
								},
								{
									"index": 19,
									"stationID": 341,
									"stationName": "남부터미널",
									"x": "127.016288",
									"y": "37.484917"
								},
								{
									"index": 20,
									"stationID": 342,
									"stationName": "양재",
									"x": "127.034022",
									"y": "37.484557"
								},
								{
									"index": 21,
									"stationID": 343,
									"stationName": "매봉",
									"x": "127.046921",
									"y": "37.487038"
								},
								{
									"index": 22,
									"stationID": 344,
									"stationName": "도곡",
									"x": "127.055349",
									"y": "37.490892"
								},
								{
									"index": 23,
									"stationID": 345,
									"stationName": "대치",
									"x": "127.063442",
									"y": "37.494587"
								},
								{
									"index": 24,
									"stationID": 346,
									"stationName": "학여울",
									"x": "127.070579",
									"y": "37.496698"
								},
								{
									"index": 25,
									"stationID": 347,
									"stationName": "대청",
									"x": "127.079541",
									"y": "37.493608"
								},
								{
									"index": 26,
									"stationID": 348,
									"stationName": "일원",
									"x": "127.084063",
									"y": "37.483871"
								},
								{
									"index": 27,
									"stationID": 349,
									"stationName": "수서",
									"x": "127.102153",
									"y": "37.487477"
								},
								{
									"index": 28,
									"stationID": 350,
									"stationName": "가락시장",
									"x": "127.117692",
									"y": "37.49222"
								},
								{
									"index": 29,
									"stationID": 351,
									"stationName": "경찰병원",
									"x": "127.124212",
									"y": "37.495702"
								},
								{
									"index": 30,
									"stationID": 352,
									"stationName": "오금",
									"x": "127.128828",
									"y": "37.502689"
								}
							]
						}
					},
					{
						"trafficType": 3,
						"distance": 302,
						"sectionTime": 5
					}
				]
			},
}

**Comment by HanBI24** [comment]
확장으로 이동
